export const ERROR_CODES = {
  SESSION_MISSING: 'SESSION_MISSING',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  TRANSACTION_NOT_FOUND: 'TRANSACTION_NOT_FOUND',
} as const;
